name: "OWASP ZAP"

# follow standard Code Scanning triggers
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: List files
        run: ls -la ${{ github.workspace }}

      - name: Display file contents
        run: cat ${{ github.workspace }}/openapi-owasp.json

      # - name: ZAP Scan
      #   uses: zaproxy/action-api-scan@v0.6.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     format: openapi
      #     target: ${{ github.workspace }}/openapi-owasp.json
      #   env:
      #     ZAP_AUTH_HEADER: "Ocp-Apim-Subscription-Key"
      #     ZAP_AUTH_HEADER_VALUE: "${{ secrets.APIM_SUBSCRIPTION_KEY }}"