name: "Stackhawk scan"

# follow standard Code Scanning triggers
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  stackhawk_scan:
    runs-on: ubuntu-latest
    name: Stackhawk Scan
    steps:
        
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Scan my app
      uses: stackhawk/hawkscan-action@v2.1.3
      with:
        apiKey: ${{ secrets.HAWK_API_KEY }}
      env:
        APIM_SUBSCRIPTION_KEY: ${{ secrets.APIM_SUBSCRIPTION_KEY }}
    


     

